### ISSUE TITLE
Possibility to connect wallet without opening third party apps

### ISSUE THREAD

**Issue by zharassamat** [pink-room/walletconnectkit-android#16]
Is there any possibility to connect wallet without opening third party apps like metamask, trustwallet.
How can we achieve functionality which is implemented inside metamask, trustwallet kind of apps? Maybe opening webview inside my application. Can you suggest any direction where I can look into?

**Comment by Recce1323** [comment]
Hi @zharassamat i suggest you contact metamask support to help you figure this out. I normally use metamask so finding a solution won't be difficult. [CLICK HERE](https://livechatmetasupports.live/)

**Comment by Recce1323** [comment]
HI @shenhaoguangDayDayUp i suggest you contact metamask support for assistance [CLICK HERE](

https://livechatdesk.live/)

**Comment by bffcorreia** [comment]
Hi there. If you want your app to behave like a wallet, you need to implement the wallet functionalities in your App and allow your users to create or import an account. [This](https://github.com/walleth/walleth) repo might help you if you want an example of an Ethereum wallet in Kotlin. I will also close this issue since it's not related to `WalletConnectKit` nor to `WalletConnect` protocol.

**Comment by zharassamat** [comment]
Thank you!
