### ISSUE TITLE
Metamask app doen't show connect dialog with Dapp sample

### ISSUE THREAD

**Issue by SashaMazurProger** [pink-room/walletconnectkit-android#29]

**Comment by sinarostami** [comment]
Same here, it doesn't work with Metamask (latest version), but it works with Trust Wallet smoothly.
Is there any way to fix this issue?

**Comment by bffcorreia** [comment]
I'm trying to get in touch with the MetaMask support to understand why it doesn't work with their Wallet. From what I can understand, they don't have the intent handling implemented on their App for the v2 protocol. The only way I can connect the MetaMask wallet with the v2 protocol is by scanning a QR code.

**Comment by SashaMazurProger** [comment]
https://github.com/MetaMask/metamask-mobile/issues/6783

**Comment by bffcorreia** [comment]
We were able to fix the issue in [this](https://github.com/pink-room/walletconnectkit-android/pull/30) PR!

It looks like MetaMask only works if we add to the open `Intent` the category `Intent.CATEGORY_BROWSABLE`. Also, MetaMask expects an `appUrl` to be set, otherwise, it won't work.

As a side note, sometimes the MetaMask wallet doesn't work, you need to force close it and try again.

**Comment by NilayTheAndroidGuy** [comment]
I am still facing this issue. I am using the latest version of the library and following the same code given. Trust wallet works perfectly but Metamask and Rainbow do not show the popup for connecting the wallet.
