### ISSUE TITLE
Q: Does this library supports multichain connect?

### ISSUE THREAD

**Issue by y9san9** [pink-room/walletconnectkit-android#9]
I need this, since my application is the application for multichain swaps and it needs to be connected simultaneously to a bunch of different web3-compatible chains

**Comment by bffcorreia** [comment]
**Short answer:** no.

**Long answer:** The WalletConnect v1 protocol is not chain agnostic. This means that it assumes that both parties communicate via EVM-compatible chains. In theory, it should be possible to extend the WalletConnect or WalletConnectKit libraries in order to pass a chainId parameter and switch between EVM-compatible chains. However, this might be tricky and not very user-friendly. With WalletConnect v2 this is not a problem, since the protocol is chain agnostic and they support connecting to multiple chains simultaneously. However, the v2 protocol is still currently being integrated into Wallets. The roadmap should be until the end of Q1 this year. Then, we will try to migrate the WalletConnectKit to also support the v2 as soon as possible.
